version: '3.9'
services:
  budgetam_angular:
    restart: always
    build:
      context: angular_application
    ports:
      - 80:4200
    depends_on:
      - budgetam_flask
  
  budgetam_flask:
    restart: always
    build:
      context: backend
    command: bash -c "python3 -m api.v0.entrypoint"
    environment:
      - MYSQL_USER=budgetam_backend_user
      - MYSQL_PWD=helloworld2024
      - MYSQL_HOST=budgetam_mysql_db
      - MYSQL_DB=budgetam_db
      - TYPE_STORAGE=db
    depends_on:
      - budgetam_mysql_db

  budgetam_mysql_db:
    image: mysql:5.7-debian
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=helloworld2023
      - MYSQL_DATABASE=budgetam_db
      - MYSQL_USER=budgetam_backend_user
      - MYSQL_PASSWORD=helloworld2024
    ports:
      - 33070:3306
